# Generated by Django 5.0.6 on 2024-06-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('referencia', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('tienda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigoTienda', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oferta', models.CharField(max_length=40)),
                ('tienda_donde_aplica', models.CharField(max_length=50)),
                ('porcentaje_oferta', models.IntegerField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPreEntrega3.tienda')),
            ],
        ),
    ]
