# Generated by Django 5.0.6 on 2024-06-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPreEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='codigoTienda',
            field=models.IntegerField(),
        ),
    ]
